var funcs = [];

funcs[0] = function(){
    document.writeln('   <div class="preloader">');
    document.writeln('        <div class="preloader__ring">');
    document.writeln('            <div class="preloader__sector">G</div>');
    document.writeln('            <div class="preloader__sector">a</div>');
    document.writeln('            <div class="preloader__sector">m</div>');
    document.writeln('            <div class="preloader__sector">e</div>');
    document.writeln('            <div class="preloader__sector">s</div>');
    document.writeln('            <div class="preloader__sector">.</div>');
    document.writeln('            <div class="preloader__sector">.</div>');
    document.writeln('            <div class="preloader__sector">.</div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('        </div>');
    document.writeln('        <div class="preloader__ring">');
    document.writeln('            <div class="preloader__sector">B</div>');
    document.writeln('            <div class="preloader__sector">y</div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector">d</div>');
    document.writeln('            <div class="preloader__sector">u</div>');
    document.writeln('            <div class="preloader__sector">c</div>');
    document.writeln('            <div class="preloader__sector">k</div>');
    document.writeln('            <div class="preloader__sector">.</div>');
    document.writeln('            <div class="preloader__sector">.</div>');
    document.writeln('            <div class="preloader__sector">.</div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('            <div class="preloader__sector"></div>');
    document.writeln('        </div>');
    document.writeln('    </div>');
    document.writeln('');
    document.writeln('');
    document.writeln('    <style>');
    document.writeln('        * {');
    document.writeln('  border: 0;');
    document.writeln('  box-sizing: border-box;');
    document.writeln('  margin: 0;');
    document.writeln('  padding: 0; }');
    document.writeln('');
    document.writeln('\\:root {');
    document.writeln('  font-size: calc(16px + (24 - 16)*(100vw - 320px)/ (1280 - 320)); }');
    document.writeln('');
    document.writeln('body, .preloader {');
    document.writeln('  display: flex; }');
    document.writeln('');
    document.writeln('body {');
    document.writeln('      background-image: radial-gradient(circle, #171424, #000); ');
    document.writeln('  color: #3df1f1;');
    document.writeln('  font: 1em Dosis, sans-serif;');
    document.writeln('  height: 100vh;');
    document.writeln('  line-height: 1.5;');
    document.writeln('  perspective: 40em; }');
    document.writeln('');
    document.writeln('.preloader {');
    document.writeln('  animation: tiltSpin 8s linear infinite;');
    document.writeln('  flex-direction: column;');
    document.writeln('  justify-content: center;');
    document.writeln('  align-items: center;');
    document.writeln('  margin: auto;');
    document.writeln('  width: 17em;');
    document.writeln('  height: 17em; }');
    document.writeln('  .preloader, .preloader__ring {');
    document.writeln('    transform-style: preserve-3d; }');
    document.writeln('  .preloader__ring {');
    document.writeln('    animation-name: spin;');
    document.writeln('    animation-duration: 4s;');
    document.writeln('    animation-timing-function: inherit;');
    document.writeln('    animation-iteration-count: inherit;');
    document.writeln('    font-size: 2em;');
    document.writeln('    position: relative;');
    document.writeln('    height: 3rem;');
    document.writeln('    width: 1.5rem; }');
    document.writeln('    .preloader__ring:nth-child(even) {');
    document.writeln('      animation-direction: reverse; }');
    document.writeln('  .preloader__sector {');
    document.writeln('    font-weight: 600;');
    document.writeln('    position: absolute;');
    document.writeln('    top: 0;');
    document.writeln('    left: 0;');
    document.writeln('    text-align: center;');
    document.writeln('    text-transform: uppercase;');
    document.writeln('    transform: translateZ(7rem); }');
    document.writeln('    .preloader__sector, .preloader__sector:empty:before {');
    document.writeln('      display: inline-block;');
    document.writeln('      width: 100%;');
    document.writeln('      height: 100%; }');
    document.writeln('    .preloader__sector:empty:before {');
    document.writeln('      background: linear-gradient(transparent 45%, currentColor 45% 55%, transparent 55%);');
    document.writeln('      content: ""; }');
    document.writeln('    .preloader__sector:nth-child(2) {');
    document.writeln('      transform: rotateY(12deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(3) {');
    document.writeln('      transform: rotateY(24deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(4) {');
    document.writeln('      transform: rotateY(36deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(5) {');
    document.writeln('      transform: rotateY(48deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(6) {');
    document.writeln('      transform: rotateY(60deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(7) {');
    document.writeln('      transform: rotateY(72deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(8) {');
    document.writeln('      transform: rotateY(84deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(9) {');
    document.writeln('      transform: rotateY(96deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(10) {');
    document.writeln('      transform: rotateY(108deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(11) {');
    document.writeln('      transform: rotateY(120deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(12) {');
    document.writeln('      transform: rotateY(132deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(13) {');
    document.writeln('      transform: rotateY(144deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(14) {');
    document.writeln('      transform: rotateY(156deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(15) {');
    document.writeln('      transform: rotateY(168deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(16) {');
    document.writeln('      transform: rotateY(180deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(17) {');
    document.writeln('      transform: rotateY(192deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(18) {');
    document.writeln('      transform: rotateY(204deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(19) {');
    document.writeln('      transform: rotateY(216deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(20) {');
    document.writeln('      transform: rotateY(228deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(21) {');
    document.writeln('      transform: rotateY(240deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(22) {');
    document.writeln('      transform: rotateY(252deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(23) {');
    document.writeln('      transform: rotateY(264deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(24) {');
    document.writeln('      transform: rotateY(276deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(25) {');
    document.writeln('      transform: rotateY(288deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(26) {');
    document.writeln('      transform: rotateY(300deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(27) {');
    document.writeln('      transform: rotateY(312deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(28) {');
    document.writeln('      transform: rotateY(324deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(29) {');
    document.writeln('      transform: rotateY(336deg) translateZ(7rem); }');
    document.writeln('    .preloader__sector:nth-child(30) {');
    document.writeln('      transform: rotateY(348deg) translateZ(7rem); }');
    document.writeln('');
    document.writeln('/* Animations */');
    document.writeln('@keyframes tiltSpin {');
    document.writeln('  from {');
    document.writeln('    transform: rotateY(0) rotateX(30deg); }');
    document.writeln('  to {');
    document.writeln('    transform: rotateY(1turn) rotateX(30deg); } }');
    document.writeln('');
    document.writeln('@keyframes spin {');
    document.writeln('  from {');
    document.writeln('    transform: rotateY(0); }');
    document.writeln('  to {');
    document.writeln('    transform: rotateY(1turn); } }');
    document.writeln('');
    document.writeln('    </style>');
    
}
funcs[1] = function(){
    document.writeln(' <div class="container">');
document.writeln('        <div class="box">');
document.writeln('          <span style="--i: 1">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 2">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 3">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 4">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 5">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 6">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 7">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 8">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 9">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 10">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 11">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 12">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 13">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 14">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 15">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('          <span style="--i: 16">');
document.writeln('            <i>duck</i>');
document.writeln('            by');
document.writeln('            <i>duck</i>');
document.writeln('          </span>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('');
document.writeln('');
document.writeln('      <style>');
document.writeln('      @import url(\'https://fonts.googleapis.com/css2?family=Heebo:wght@400;600&family=Poppins:wght@100;500;600;800;900&family=Lobster+Two:ital,wght@0,400;0,700;1,400&display=swap\');');
document.writeln('/* GLOBAL CONFIG RESET */');
document.writeln(' * {');
document.writeln('	 box-sizing: border-box;');
document.writeln('	 margin: 0;');
document.writeln('	 padding: 0;');
document.writeln('	 font-family: \'Poppins\', sans-serif;');
document.writeln('}');
document.writeln(' select:focus, input:focus, button:focus {');
document.writeln('	 outline: none;');
document.writeln('}');
document.writeln('/* -------- BODY DISPLAY --------- */');
document.writeln(' body {');
document.writeln('	 	 background-image: radial-gradient(circle, #171424, #000);');
document.writeln('	 overflow: hidden;');
document.writeln('	 display: flex;');
document.writeln('	 justify-content: center;');
document.writeln('	 align-items: center;');
document.writeln('	 min-height: 100vh;');
document.writeln('}');
document.writeln('/* -------- TYPE SELECTORS --------- */');
document.writeln('/* -------- CLASS --------- */');
document.writeln(' .container {');
document.writeln('	 display: flex;');
document.writeln('	 justify-content: center;');
document.writeln('	 align-items: center;');
document.writeln('}');
document.writeln(' .container .box {');
document.writeln('	 transform-style: preserve-3d;');
document.writeln('	 animation: animate 7s ease-in-out infinite alternate;');
document.writeln('}');
document.writeln(' .container .box span {');
document.writeln('	 /* background: linear-gradient(90deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.5) 90%, transparent); */');
document.writeln('	 text-transform: uppercase;');
document.writeln('	 line-height: 0.76em;');
document.writeln('	 position: absolute;');
document.writeln('	 color: #fff;');
document.writeln('	 font-size: 3.5em;');
document.writeln('	 white-space: nowrap;');
document.writeln('	 font-weight: bold;');
document.writeln('	 padding: 0px 10px;');
document.writeln('	 transform-style: preserve-3d;');
document.writeln('	 /* text-shadow: 0 10px 15px rgba(0, 0, 0, 0.3); */');
document.writeln('	 transform: translate(-50%, -50%) rotateX(calc(var(--i) * 22.5deg)) translateZ(109px);');
document.writeln('}');
document.writeln(' .container .box span i {');
document.writeln('	 font-style: initial;');
document.writeln('}');
document.writeln(' .container .box span i:nth-child(1) {');
document.writeln('	 color: #5c5fc4;');
document.writeln('}');
document.writeln(' .container .box span i:nth-child(2) {');
document.writeln('	 color: #c4c15c;');
document.writeln('}');
document.writeln(' @keyframes animate {');
document.writeln('	 0% {');
document.writeln('		 transform: perspective(500px) rotateX(0deg) rotate(5deg);');
document.writeln('	}');
document.writeln('	 100% {');
document.writeln('		 transform: perspective(50px) rotateX(360deg) rotate(5deg);');
document.writeln('	}');
document.writeln('}');
document.writeln('/* -------- PSEUDO CLASS --------- */');
document.writeln('/* -------- MEDIA QUERY --------- */');
document.writeln(' ');
document.writeln('      </style>');

}
funcs[2] = function(){
    document.writeln('    <link rel="stylesheet" href="./1.css">');
    document.writeln('<div class="house" id="h">');
document.writeln('  <div class="h-lights">');
document.writeln('      <div class="h-light"></div>');
document.writeln('      <div class="h-light"></div>');
document.writeln('      <div class="h-light"></div>');
document.writeln('      <div class="h-light"></div>');
document.writeln('      <div class="h-light"></div>');
document.writeln('      <div class="h-light"></div>');
document.writeln('  </div>');
document.writeln('  <div class="h-shadow"></div>');
document.writeln('  <div class="alt">');
document.writeln('      <div class="alt__front face"> </div>');
document.writeln('      <div class="alt__back face"> </div>');
document.writeln('      <div class="alt__right face"> </div>');
document.writeln('      <div class="alt__left face"> </div>');
document.writeln('      <div class="alt__top face">');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('          <div class="light"></div>');
document.writeln('      </div>');
document.writeln('      <div class="alt__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="alb">');
document.writeln('      <div class="alb__front face"> </div>');
document.writeln('      <div class="alb__back face"> </div>');
document.writeln('      <div class="alb__right face"> </div>');
document.writeln('      <div class="alb__left face"> </div>');
document.writeln('      <div class="alb__top face"> </div>');
document.writeln('      <div class="alb__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="arb">');
document.writeln('      <div class="arb__front face"> </div>');
document.writeln('      <div class="arb__back face"> </div>');
document.writeln('      <div class="arb__right face"> </div>');
document.writeln('      <div class="arb__left face"> </div>');
document.writeln('      <div class="arb__top face"> </div>');
document.writeln('      <div class="arb__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="blt">');
document.writeln('      <div class="blt__front face"> </div>');
document.writeln('      <div class="blt__back face"> </div>');
document.writeln('      <div class="blt__right face"> </div>');
document.writeln('      <div class="blt__left face"> </div>');
document.writeln('      <div class="blt__top face"> </div>');
document.writeln('      <div class="blt__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="blt2">');
document.writeln('      <div class="blt2__front face"> </div>');
document.writeln('      <div class="blt2__back face"> </div>');
document.writeln('      <div class="blt2__right face"> </div>');
document.writeln('      <div class="blt2__left face"> </div>');
document.writeln('      <div class="blt2__top face"> </div>');
document.writeln('      <div class="blt2__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="blb">');
document.writeln('      <div class="blb__front face"> </div>');
document.writeln('      <div class="blb__back face"> </div>');
document.writeln('      <div class="blb__right face"> </div>');
document.writeln('      <div class="blb__left face"> </div>');
document.writeln('      <div class="blb__top face"> </div>');
document.writeln('      <div class="blb__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="blb2">');
document.writeln('      <div class="blb2__front face"> </div>');
document.writeln('      <div class="blb2__back face"> </div>');
document.writeln('      <div class="blb2__right face"> </div>');
document.writeln('      <div class="blb2__left face"> </div>');
document.writeln('      <div class="blb2__top face"> </div>');
document.writeln('      <div class="blb2__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="puerta-c">');
document.writeln('      <div class="puerta">');
document.writeln('          <div class="puerta__front face"> </div>');
document.writeln('          <div class="puerta__back face"> </div>');
document.writeln('          <div class="puerta__right face"> </div>');
document.writeln('          <div class="puerta__left face"> </div>');
document.writeln('          <div class="puerta__top face"> </div>');
document.writeln('          <div class="puerta__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="puerta-l">');
document.writeln('          <div class="puerta-l__front face"> </div>');
document.writeln('          <div class="puerta-l__back face"> </div>');
document.writeln('          <div class="puerta-l__right face"> </div>');
document.writeln('          <div class="puerta-l__left face"> </div>');
document.writeln('          <div class="puerta-l__top face"> </div>');
document.writeln('          <div class="puerta-l__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="puerta-r">');
document.writeln('          <div class="puerta-r__front face"> </div>');
document.writeln('          <div class="puerta-r__back face"> </div>');
document.writeln('          <div class="puerta-r__right face"> </div>');
document.writeln('          <div class="puerta-r__left face"> </div>');
document.writeln('          <div class="puerta-r__top face"> </div>');
document.writeln('          <div class="puerta-r__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="puerta-t">');
document.writeln('          <div class="puerta-t__front face"> </div>');
document.writeln('          <div class="puerta-t__back face"> </div>');
document.writeln('          <div class="puerta-t__right face"> </div>');
document.writeln('          <div class="puerta-t__left face"> </div>');
document.writeln('          <div class="puerta-t__top face"> </div>');
document.writeln('          <div class="puerta-t__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('  </div>');
document.writeln('  <div class="cuadro-l">');
document.writeln('      <div class="cuadro-l__front face"> </div>');
document.writeln('      <div class="cuadro-l__back face"> </div>');
document.writeln('      <div class="cuadro-l__right face"> </div>');
document.writeln('      <div class="cuadro-l__left face"> </div>');
document.writeln('      <div class="cuadro-l__top face"> </div>');
document.writeln('      <div class="cuadro-l__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="cuadro-r">');
document.writeln('      <div class="cuadro-r__front face"> </div>');
document.writeln('      <div class="cuadro-r__back face"> </div>');
document.writeln('      <div class="cuadro-r__right face"> </div>');
document.writeln('      <div class="cuadro-r__left face"> </div>');
document.writeln('      <div class="cuadro-r__top face"> </div>');
document.writeln('      <div class="cuadro-r__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="librero">');
document.writeln('      <div class="librero__front face"> </div>');
document.writeln('      <div class="librero__back face"> </div>');
document.writeln('      <div class="librero__right face"> </div>');
document.writeln('      <div class="librero__left face"> </div>');
document.writeln('      <div class="librero__top face"> </div>');
document.writeln('      <div class="librero__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="libros">');
document.writeln('      <div class="libro">');
document.writeln('          <div class="libro__front face"> </div>');
document.writeln('          <div class="libro__back face"> </div>');
document.writeln('          <div class="libro__right face"> </div>');
document.writeln('          <div class="libro__left face"> </div>');
document.writeln('          <div class="libro__top face"> </div>');
document.writeln('          <div class="libro__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="libro">');
document.writeln('          <div class="libro__front face"> </div>');
document.writeln('          <div class="libro__back face"> </div>');
document.writeln('          <div class="libro__right face"> </div>');
document.writeln('          <div class="libro__left face"> </div>');
document.writeln('          <div class="libro__top face"> </div>');
document.writeln('          <div class="libro__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="libro">');
document.writeln('          <div class="libro__front face"> </div>');
document.writeln('          <div class="libro__back face"> </div>');
document.writeln('          <div class="libro__right face"> </div>');
document.writeln('          <div class="libro__left face"> </div>');
document.writeln('          <div class="libro__top face"> </div>');
document.writeln('          <div class="libro__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="libro">');
document.writeln('          <div class="libro__front face"> </div>');
document.writeln('          <div class="libro__back face"> </div>');
document.writeln('          <div class="libro__right face"> </div>');
document.writeln('          <div class="libro__left face"> </div>');
document.writeln('          <div class="libro__top face"> </div>');
document.writeln('          <div class="libro__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="libro">');
document.writeln('          <div class="libro__front face"> </div>');
document.writeln('          <div class="libro__back face"> </div>');
document.writeln('          <div class="libro__right face"> </div>');
document.writeln('          <div class="libro__left face"> </div>');
document.writeln('          <div class="libro__top face"> </div>');
document.writeln('          <div class="libro__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="libro">');
document.writeln('          <div class="libro__front face"> </div>');
document.writeln('          <div class="libro__back face"> </div>');
document.writeln('          <div class="libro__right face"> </div>');
document.writeln('          <div class="libro__left face"> </div>');
document.writeln('          <div class="libro__top face"> </div>');
document.writeln('          <div class="libro__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('  </div>');
document.writeln('  <div class="fotos">');
document.writeln('      <div class="foto">');
document.writeln('          <div class="foto__front face"> </div>');
document.writeln('          <div class="foto__back face"> </div>');
document.writeln('          <div class="foto__right face"> </div>');
document.writeln('          <div class="foto__left face"> </div>');
document.writeln('          <div class="foto__top face"> </div>');
document.writeln('          <div class="foto__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="foto">');
document.writeln('          <div class="foto__front face"> </div>');
document.writeln('          <div class="foto__back face"> </div>');
document.writeln('          <div class="foto__right face"> </div>');
document.writeln('          <div class="foto__left face"> </div>');
document.writeln('          <div class="foto__top face"> </div>');
document.writeln('          <div class="foto__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('  </div>');
document.writeln('  <div class="cajas">');
document.writeln('      <div class="caja">');
document.writeln('          <div class="caja__front face"> </div>');
document.writeln('          <div class="caja__back face"> </div>');
document.writeln('          <div class="caja__right face"> </div>');
document.writeln('          <div class="caja__left face"> </div>');
document.writeln('          <div class="caja__top face"> </div>');
document.writeln('          <div class="caja__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="caja">');
document.writeln('          <div class="caja__front face"> </div>');
document.writeln('          <div class="caja__back face"> </div>');
document.writeln('          <div class="caja__right face"> </div>');
document.writeln('          <div class="caja__left face"> </div>');
document.writeln('          <div class="caja__top face"> </div>');
document.writeln('          <div class="caja__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="caja">');
document.writeln('          <div class="caja__front face"> </div>');
document.writeln('          <div class="caja__back face"> </div>');
document.writeln('          <div class="caja__right face"> </div>');
document.writeln('          <div class="caja__left face"> </div>');
document.writeln('          <div class="caja__top face"> </div>');
document.writeln('          <div class="caja__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('  </div>');
document.writeln('  <div class="tv">');
document.writeln('      <div class="tv__front face"> </div>');
document.writeln('      <div class="tv__back face"> </div>');
document.writeln('      <div class="tv__right face"> </div>');
document.writeln('      <div class="tv__left face"> </div>');
document.writeln('      <div class="tv__top face"> </div>');
document.writeln('      <div class="tv__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="repisa-t">');
document.writeln('      <div class="repisa-t__front face"> </div>');
document.writeln('      <div class="repisa-t__back face"> </div>');
document.writeln('      <div class="repisa-t__right face"> </div>');
document.writeln('      <div class="repisa-t__left face"> </div>');
document.writeln('      <div class="repisa-t__top face"> </div>');
document.writeln('      <div class="repisa-t__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="repisa-b">');
document.writeln('      <div class="repisa-b__front face"> </div>');
document.writeln('      <div class="repisa-b__back face"> </div>');
document.writeln('      <div class="repisa-b__right face"> </div>');
document.writeln('      <div class="repisa-b__left face"> </div>');
document.writeln('      <div class="repisa-b__top face"> </div>');
document.writeln('      <div class="repisa-b__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="bocina-l">');
document.writeln('      <div class="bocina-l__front face"> </div>');
document.writeln('      <div class="bocina-l__back face"> </div>');
document.writeln('      <div class="bocina-l__right face"> </div>');
document.writeln('      <div class="bocina-l__left face"> </div>');
document.writeln('      <div class="bocina-l__top face"> </div>');
document.writeln('      <div class="bocina-l__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="bocina-r">');
document.writeln('      <div class="bocina-r__front face"> </div>');
document.writeln('      <div class="bocina-r__back face"> </div>');
document.writeln('      <div class="bocina-r__right face"> </div>');
document.writeln('      <div class="bocina-r__left face"> </div>');
document.writeln('      <div class="bocina-r__top face"> </div>');
document.writeln('      <div class="bocina-r__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="muro">');
document.writeln('      <div class="muro__front face"> </div>');
document.writeln('      <div class="muro__back face"> </div>');
document.writeln('      <div class="muro__right face"> </div>');
document.writeln('      <div class="muro__left face"> </div>');
document.writeln('      <div class="muro__top face"> </div>');
document.writeln('      <div class="muro__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('  <div class="sillon-c">');
document.writeln('      <div class="sillon-b">');
document.writeln('          <div class="sillon-b__front face"> </div>');
document.writeln('          <div class="sillon-b__back face"> </div>');
document.writeln('          <div class="sillon-b__right face"> </div>');
document.writeln('          <div class="sillon-b__left face"> </div>');
document.writeln('          <div class="sillon-b__top face"> </div>');
document.writeln('          <div class="sillon-b__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="sillon-t">');
document.writeln('          <div class="sillon-t__front face"> </div>');
document.writeln('          <div class="sillon-t__back face"> </div>');
document.writeln('          <div class="sillon-t__right face"> </div>');
document.writeln('          <div class="sillon-t__left face"> </div>');
document.writeln('          <div class="sillon-t__top face"> </div>');
document.writeln('          <div class="sillon-t__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="sillon-l">');
document.writeln('          <div class="sillon-l__front face"> </div>');
document.writeln('          <div class="sillon-l__back face"> </div>');
document.writeln('          <div class="sillon-l__right face"> </div>');
document.writeln('          <div class="sillon-l__left face"> </div>');
document.writeln('          <div class="sillon-l__top face"> </div>');
document.writeln('          <div class="sillon-l__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="sillon-r">');
document.writeln('          <div class="sillon-r__front face"> </div>');
document.writeln('          <div class="sillon-r__back face"> </div>');
document.writeln('          <div class="sillon-r__right face"> </div>');
document.writeln('          <div class="sillon-r__left face"> </div>');
document.writeln('          <div class="sillon-r__top face"> </div>');
document.writeln('          <div class="sillon-r__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('  </div>');
document.writeln('  <div class="mesa-c">');
document.writeln('      <div class="mesa">');
document.writeln('          <div class="mesa__front face"> </div>');
document.writeln('          <div class="mesa__back face"> </div>');
document.writeln('          <div class="mesa__right face"> </div>');
document.writeln('          <div class="mesa__left face"> </div>');
document.writeln('          <div class="mesa__top face"> </div>');
document.writeln('          <div class="mesa__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="mesa-p">');
document.writeln('          <div class="mesa-p__front face"> </div>');
document.writeln('          <div class="mesa-p__back face"> </div>');
document.writeln('          <div class="mesa-p__right face"> </div>');
document.writeln('          <div class="mesa-p__left face"> </div>');
document.writeln('          <div class="mesa-p__top face"> </div>');
document.writeln('          <div class="mesa-p__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="mesa-p">');
document.writeln('          <div class="mesa-p__front face"> </div>');
document.writeln('          <div class="mesa-p__back face"> </div>');
document.writeln('          <div class="mesa-p__right face"> </div>');
document.writeln('          <div class="mesa-p__left face"> </div>');
document.writeln('          <div class="mesa-p__top face"> </div>');
document.writeln('          <div class="mesa-p__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="mesa-p">');
document.writeln('          <div class="mesa-p__front face"> </div>');
document.writeln('          <div class="mesa-p__back face"> </div>');
document.writeln('          <div class="mesa-p__right face"> </div>');
document.writeln('          <div class="mesa-p__left face"> </div>');
document.writeln('          <div class="mesa-p__top face"> </div>');
document.writeln('          <div class="mesa-p__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="mesa-p">');
document.writeln('          <div class="mesa-p__front face"> </div>');
document.writeln('          <div class="mesa-p__back face"> </div>');
document.writeln('          <div class="mesa-p__right face"> </div>');
document.writeln('          <div class="mesa-p__left face"> </div>');
document.writeln('          <div class="mesa-p__top face"> </div>');
document.writeln('          <div class="mesa-p__bottom face"> </div>');
document.writeln('      </div>');
document.writeln('      <div class="mesa-shadow"></div>');
document.writeln('  </div>');
document.writeln('  <div class="tablet">');
document.writeln('      <div class="tablet__front face"> </div>');
document.writeln('      <div class="tablet__back face"> </div>');
document.writeln('      <div class="tablet__right face"> </div>');
document.writeln('      <div class="tablet__left face"> </div>');
document.writeln('      <div class="tablet__top face"> </div>');
document.writeln('      <div class="tablet__bottom face"> </div>');
document.writeln('  </div>');
document.writeln('</div>');


}
funcs[3] = function(){
    // document.writeln('<link rel="stylesheet" href="./2.css">');
}
funcs[4] = function(){
document.writeln('    <link rel="stylesheet" href="./3.css">');
document.write(' <div class="bubbles">');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('    <div class="bubble"></div>');
document.write('</div>');

}

funcs[5] = function(){
    document.write('<html lang="en">');
document.write('<head>');
document.write('    <meta charset="UTF-8">');
document.write('    <meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('    <title>Matrix digital rain</title>');
document.write('</head>');
document.write('<body>');
document.write('    <style>');
document.write('        html {');
document.write('    background: black;');
document.write('    height: 100%;');
document.write('    overflow: hidden;');
document.write('}');
document.write('');
document.write('body {');
document.write('    margin: 0;');
document.write('    padding: 0;');
document.write('    height: 100vh;');
document.write('    width: 100%;');
document.write('}');
document.write('Matrix {');
document.write('    width: 100%;');
document.write('    height: 100vh;');
document.write('}');
document.write('    </style>');
document.write('    <canvas id="Matrix"></canvas>');
document.write('');
document.write('    <script>const canvas = document.getElementById(\'Matrix\');');
document.write('        const context = canvas.getContext(\'2d\');');
document.write('        ');
document.write('        canvas.width = window.innerWidth;');
document.write('        canvas.height = window.innerHeight;');
document.write('        ');
document.write('        const katakana = \'アァカサタナハマヤャラワガザダバパイィキシチニヒミリヰギジヂビピウゥクスツヌフムユュルグズブヅプエェケセテネヘメレヱゲゼデベペオォコソトノホモヨョロヲゴゾドボポヴッン\';');
document.write('        const latin = \'ABCDEFGHIJKLMNOPQRSTUVWXYZ\';');
document.write('        const nums = \'0123456789\';');
document.write('        const ouch = "duck_duck_duck";');
document.write('        ');
document.write('        const alphabet = katakana + latin + nums + ouch;');
document.write('        ');
document.write('        const fontSize = 16;');
document.write('        const columns = canvas.width/fontSize;');
document.write('        ');
document.write('        const rainDrops = [];');
document.write('        ');
document.write('        for( let x = 0; x < columns; x++ ) {');
document.write('            rainDrops[x] = 1;');
document.write('        }');
document.write('        ');
document.write('        const draw = () => {');
document.write('            context.fillStyle = \'rgba(0, 0, 0, 0.05)\';');
document.write('            context.fillRect(0, 0, canvas.width, canvas.height);');
document.write('            ');
document.write('            context.fillStyle = \'#0F0\';');
document.write('            context.font = fontSize + \'px monospace\';');
document.write('        ');
document.write('            for(let i = 0; i < rainDrops.length; i++)');
document.write('            {');
document.write('                const text = alphabet.charAt(Math.floor(Math.random() * alphabet.length));');
document.write('                context.fillText(text, i*fontSize, rainDrops[i]*fontSize);');
document.write('                ');
document.write('                if(rainDrops[i]*fontSize > canvas.height && Math.random() > 0.975){');
document.write('                    rainDrops[i] = 0;');
document.write('                }');
document.write('                rainDrops[i]++;');
document.write('            }');
document.write('        };');
document.write('        ');
document.write('        setInterval(draw, 30);');
document.write('        </script>');
document.write('</body>');
document.write('</html>');
document.write('');

}

// funcs[6] = function(){
//     document.writeln(' <link rel="stylesheet" href="./1.css">');
// }
    
    
    function back() {

    var rand = parseInt(Math.random()*funcs.length);  
    funcs[rand]();
    }